"""Portable layer and asset inspector; no external scripts or services."""
import html
import json
from .layout import layout_scene


def inspector_html(scene, svg):
    data = json.dumps({'scene': scene.to_dict(), 'layout': layout_scene(scene).to_dict()}, ensure_ascii=False).replace('<', '\\u003c')
    template = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SceneLyr inspector · Layers & assets</title><style>
*{box-sizing:border-box}body{margin:0;font:14px system-ui;color:#183047;background:#edf1f5}header{padding:18px 24px;background:white;border-bottom:1px solid #d8e1e8}h1{font-size:20px;margin:0}p{line-height:1.5}.workspace{display:grid;grid-template-columns:240px minmax(300px,1fr) 280px;min-height:85vh}aside{background:#fff;padding:18px;overflow:auto}main{padding:22px;overflow:auto}svg{width:100%;height:auto;min-width:560px}.tree details{margin:12px 0}.tree summary{font-weight:650;cursor:pointer}.tree button{display:block;width:100%;text-align:left;background:transparent;border:0;border-radius:6px;padding:8px;color:inherit;cursor:pointer}.tree button:hover,.tree button.active{background:#e7f2f5;color:#006777}.tree .children{border-left:1px solid #ccdbe3;margin:8px 0 8px 4px;padding-left:8px}.muted{color:#667a8a;font-size:12px}.path{overflow-wrap:anywhere;font:12px ui-monospace;background:#f1f5f7;padding:9px;border-radius:6px}dt{font-size:12px;color:#657786;margin-top:14px}dd{margin:4px 0;overflow-wrap:anywhere}.notice{padding:12px;background:#fff7df;border-radius:8px;font-size:12px}[data-scene-id],[data-edge-id]{cursor:pointer}.selected>:first-child{stroke:#008b9a!important;stroke-width:4!important}a{color:#006777}@media(max-width:900px){.workspace{grid-template-columns:190px minmax(0,1fr)}.properties{grid-column:1/-1}svg{min-width:0}}
</style><header><h1 id="title"></h1><p class="muted">Layers · Connections · Stored assets</p></header><div class="workspace"><aside class="tree"><details open><summary>Diagram layers</summary><div id="layers" class="children"></div></details><details open><summary>Connections</summary><div id="connections" class="children"></div></details><details open><summary>Assets</summary><div id="assets" class="children"></div></details><details open><summary>Arrow debug</summary><div id="arrowDebug" class="children"></div></details></aside><main>__SVG__<p class="notice" id="notice"></p></main><aside class="properties"><h3 id="selectionTitle">Scene storage</h3><div id="properties"></div><h3>Saved location</h3><div id="folder" class="path"></div><p class="muted">Each object is stored as an editable SVG in assets/. The manifest records its source bounds and current layout position.</p><h3>Files</h3><div id="files"></div></aside></div><script id="data" type="application/json">__DATA__</script><script>
const {scene,layout}=JSON.parse(document.getElementById('data').textContent);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('title').textContent=scene.intent?.title||scene.id;$('folder').textContent=scene.metadata.dataFolder||'Not saved';
$('notice').textContent=scene.metadata.correctionNote|| (scene.metadata.requiresReview?'Review required: detected labels and connections may be incomplete.':'Select a layer to inspect its position and stored asset.');
function fields(values){$('properties').innerHTML='<dl>'+Object.entries(values).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(typeof v==='object'?JSON.stringify(v):v)}</dd>`).join('')+'</dl>'}
function select(id,type){document.querySelectorAll('.selected,.active').forEach(e=>e.classList.remove('selected','active'));document.querySelectorAll('[data-item]').forEach(e=>{if(e.dataset.item===id)e.classList.add('active')});const n=scene.nodes.find(n=>n.id===id),e=scene.edges.find(e=>e.id===id);if(type==='node'&&n){document.querySelectorAll('[data-scene-id]').forEach(el=>{if(el.dataset.sceneId===id)el.classList.add('selected')});$('selectionTitle').textContent=n.label;const l=layout.nodes.find(x=>x.id===id);fields({'Layer ID':n.id,'Shape':n.metadata.shape||n.kind,'Label origin':n.metadata.labelStatus||'Semantic','Original image bounds':n.metadata.sourceBounds||'None','Current position':{x:l.x,y:l.y,width:l.width,height:l.height},'Asset file':n.metadata.assetPath||'Not saved','Source image':scene.metadata.sourceImage||'None'});}else if(e){document.querySelectorAll('[data-edge-id]').forEach(el=>{if(el.dataset.edgeId===id)el.classList.add('selected')});$('selectionTitle').textContent=e.label||'Connection';fields({'From':e.from,'To':e.to,'Origin':e.metadata?.origin||'Extracted / unspecified','Route':layout.edges.find(x=>x.id===id)?.points});}}
function button(parent,label,id,type){const b=document.createElement('button');b.textContent=label;b.dataset.item=id;b.onclick=()=>select(id,type);parent.append(b)}
const grouped=new Set();for(const g of scene.groups){const d=document.createElement('details');d.open=true;const summary=document.createElement('summary');summary.textContent=g.label;d.append(summary);const c=document.createElement('div');c.className='children';d.append(c);$('layers').append(d);for(const id of g.nodeIds){const n=scene.nodes.find(n=>n.id===id);if(n){button(c,n.label,n.id,'node');grouped.add(n.id)}}}for(const n of scene.nodes)if(!grouped.has(n.id))button($('layers'),n.label,n.id,'node');for(const e of scene.edges)button($('connections'),`${scene.nodes.find(n=>n.id===e.from)?.label} → ${scene.nodes.find(n=>n.id===e.to)?.label}${e.label?' · '+e.label:''}`,e.id,'edge');if(!scene.edges.length)$('connections').textContent='No connections';for(const n of scene.nodes)button($('assets'),n.label+' · SVG',n.id,'node');
for(const a of scene.assets){const p=document.createElement('p');p.className='path';p.textContent=(a.alt||a.id)+' — '+a.uri;$('assets').append(p)}
const debug=scene.metadata.arrowDebug;if(debug){for(const stage of debug.stages||[]){const p=document.createElement('p');p.className='path';p.textContent=stage.id+' — '+stage.file;$('arrowDebug').append(p)}const p=document.createElement('p');p.className='muted';p.textContent=(debug.candidateCount||0)+' line candidates · '+(debug.detectedEdgeCount||0)+' detected edges';$('arrowDebug').append(p)}else $('arrowDebug').textContent='No debug run saved.';
for(const name of ['scene.json','assets/manifest.json','debug/manifest.json','preview.svg','inspector.html','editable.pptx']){const p=document.createElement('div');p.className='path';p.textContent=(scene.metadata.dataFolder||'')+'/'+name;$('files').append(p)}
document.querySelectorAll('[data-scene-id]').forEach(e=>e.onclick=()=>select(e.dataset.sceneId,'node'));document.querySelectorAll('[data-edge-id]').forEach(e=>e.onclick=()=>select(e.dataset.edgeId,'edge'));fields({'Objects':scene.nodes.length,'Connections':scene.edges.length,'Scene ID':scene.id});
</script></html>'''
    return template.replace('__SVG__', svg).replace('__DATA__', data)
